### ISSUE TITLE
Requirements need updating

### ISSUE THREAD

**Issue by iotashan** [TheRealAgentK/facebook-cf-sdk#1]
Turns out it requires CF 9.0.1 because FacebookApp.cfc: line 428 uses a for-in loop, which is new in 9.0.1

http://www.adobe.com/devnet/coldfusion/articles/whatsnew_cf901.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+developer_center_tutorials+(Adobe+Developer+Center+RSS+Feed)

Scroll to "Language enhancements"

**Comment by benorama** [comment]
Indeed, requirements have been updated in the GitHub wiki Installation page and RIAForge project page.
Thanks.

**Comment by cashsavings** [comment]
Glad you reported this iotashan, I couldnt figure why I was getting the error.
