### ISSUE TITLE
userObject is not a variable

### ISSUE THREAD

**Issue by charlesr1971** [TheRealAgentK/facebook-cf-sdk#11]
This is a CF error that happens due to an 'OAuthInvalidTokenException' exception, which is usually caused by an invalid session. Although facebook data is still available, because authenticated is set to false, the information does not get displayed.

The fix:

<cfscript>
import facebook.sdk.FacebookApp;
import facebook.sdk.FacebookGraphAPI;

// Replace this with your appId and secret
APP_ID = "205551979486490";
SECRET_KEY = "9a6bd0250a238cc3fea206d3c8cdfedd";

// Create facebookApp instance
facebookApp = new FacebookApp(appId=APP_ID, secretKey=SECRET_KEY);

// We may or may not have this data based on a URL or COOKIE based session.
//
// If we get a session here, it means we found a correctly signed session using
// the Application Secret only Facebook and the Application know. We dont know
// if it is still valid until we make an API call using the session. A session
// can become invalid if it has already expired (should not be getting the
// session back in this case) or if the user logged out of Facebook.
userSession = facebookApp.getUserSession();

authenticated = false;
if (structKeyExists(userSession, "uid")) {
    try {
        facebookGraphAPI = new FacebookGraphAPI(userSession.access_token);
        userObject = facebookGraphAPI.getObject(id=userSession.uid);
        userFriends = facebookGraphAPI.getConnections(id='#userSession.uid#', type='friends', limit=10);
        userFeed = facebookGraphAPI.getConnections(id='#userSession.uid#', type='news feed', limit=10);
        authenticated = true;
    } catch (any exception) {
        // Ignore exception (OAuthInvalidTokenException), usually an invalid session
    } finally {
        facebookGraphAPI = new FacebookGraphAPI();
                                          
        if(ISDEFINED('userObject')){ 
          authenticated = true;  
        }
                                             
    }
} else {
    facebookGraphAPI = new FacebookGraphAPI();
}

// Login or logout url will be needed depending on current user state.
if (authenticated) {
    logoutUrl = facebookApp.getLogoutUrl();
} else {
    parameters = structNew();
    parameters["req_perms"] = "publish_stream";
    loginUrl = facebookApp.getLoginUrl(parameters);
}

// This call will always work since we are fetching public data.
naitik = facebookGraphAPI.getObject(id='naitik');
</cfscript>

**Comment by benorama** [comment]
You faced this issue on which example? On which line did you get the exception? 
Because, if authenticated is false, we do not use the userObject, isn't it?
