### ISSUE TITLE
Errors local CF 9

### ISSUE THREAD

**Issue by Skorpija** [TheRealAgentK/facebook-cf-sdk#12]
My CF reports issues with the following lines:
private String function getUrl(String path = "", Struct parameters = {}) {

Fixed it with:
private String function getUrl(String path = "", Struct parameters = StructNew()) {

And the following line:
for (var key in arguments.parameters) {

Fixed it with: for (key in arguments.parameters) {

Regards,
Marcel

**Comment by benorama** [comment]
Have you ColdFusion 9.0.1?
Do you get this error in ColdFusion Builder 1 or when you run the code?
ColdFusion Builder 1 does not always do a good job with syntax hi lighting...
