### ISSUE TITLE
Godaddy

### ISSUE THREAD

**Issue by lokointhehouse** [TheRealAgentK/facebook-cf-sdk#14]
godaddy does't seem to allow components in the application.cfc. is there a work around.

**Comment by benorama** [comment]
The SDK is written in 100% cfscript. 
Sorry it would requires too much work to maintain another version in CFML...

Anyway, it looks like GoDaddy is to going to discontinue ColdFusion hosting, so might try another one :
http://community.godaddy.com/godaddy/go-daddy-to-discontinue-coldfusion-support/
