### ISSUE TITLE
possible bug, possible resolution

### ISSUE THREAD

**Issue by tunameltdown** [TheRealAgentK/facebook-cf-sdk#16]
I've been struggling with this problem for the last two days and I think I've found a fix but as cfscript is not my specialty I'll just post it here:

The issue is this:
Connect to Facebook App for the first time.
Grant permissions to the app.
Page refreshes with a connection to the app.
I Click logout and I get the following error:

---

Invalid session signature in url/form session parameter

The error occurred in D:\home\genuinepixels.com\wwwroot\acme\components\FacebookApp.cfc: line 639
Called from D:\home\genuinepixels.com\wwwroot\acme\components\FacebookApp.cfc: line 309
Called from D:\home\genuinepixels.com\wwwroot\acme\widgets\reserve.cfm: line 30
Called from D:\home\genuinepixels.com\wwwroot\acme\widgets\reserve.cfm: line 1
637 :                   valid = true;
638 :               } else {
639 :                   throw(errorcode="Invalid signature", message="Invalid session signature in url/form session parameter", type="Facebook Application Security");
640 :               }
641 :           }

---

The logout does succeed (I'm successfully logged out of Facebook) but I can only clear the error by backing up one step in the browser's history, refreshing the page and then reconnecting to the app. Once I'm reconnected I can log in and out of Facebook using the "connect with..." and "logout" buttons no problem.

The workaround for me was to change line 639 from the "throw" error to "valid = false;" With this change I no longer get the CF error and I can connect and logout without any problem. 

So my updated code now reads...

```
            if (arguments.userSession["sig"] == expectedSignature) {
                valid = true;
            } else {
                valid = false;
            }
        }
        return valid;
    }

}
```

But again, cfscript not being my strength, I'm not sure if I'm creating one problem while "solving" another.

I've tried to replicate this on the example site (http://affinitiz.com/facebook-cf-sdk/examples/website/) but to no avail so perhaps it's a server issue. Or more specifically an IIS 7.5 issue.

If you would like to see an example...

With error: http://www.genuinepixels.com/acme/affinitiz/examples/website/no_error.cfm

Without error: http://www.genuinepixels.com/acme/affinitiz/examples/website/with_error.cfm

**Comment by benorama** [comment]
I'm going to release V3.1.1 of the SDK next week.
It's a complete rewrite based on the new PHP SDK V3.1.1, which implement OAuth 2.0, required for all apps from October 1st (in 2 weeks). 
Your issue might be solved with this new version.
If you want to give it a try before the official release, let me know.

**Comment by tunameltdown** [comment]
Merci!

I will wait. No problem. My implementation is still in testing. Thanks so much for writing this in the first place.

Geoff

---

Geoffrey Fudge
www.genuinepixels.com
128 Peckham Avenue
Middletown, RI 02842

ph: 401.225.0771
