### ISSUE TITLE
perms should be scope

### ISSUE THREAD

**Issue by KrunchMuffin** [TheRealAgentK/facebook-cf-sdk#17]
I get this error when adding new perms

OAuth2 specification states that 'perms' should now be called 'scope'. Please update.

**Comment by KrunchMuffin** [comment]
Looks like the all the tags haven't been updated yet? at least login-link is not. response.session should be response.authResponse.

**Comment by benorama** [comment]
Indeed "perms" have been renamed to "scope". How do you get this error?

**Comment by KrunchMuffin** [comment]
it was still written as that in the login-link template

**Comment by benorama** [comment]
Indeed the login-link has not been updated for response.session... It will be in next release. Thanks!

**Comment by logiclabz** [comment]
Facebook login connect has migrated to oauth2.0 creating Facebook Login Error as Oauth2 specification states that 'perms' should now be called 'scope' 
http://blog.logiclabz.com/javascript/facebook-login-error-oauth2-specification-states-that-perms-should-now-be-called-scope.aspx

**Comment by benorama** [comment]
Do you use the latest release of the SDK?
