### ISSUE TITLE
Example website in v3.1.1-beta2 fails

### ISSUE THREAD

**Issue by dejannenov** [TheRealAgentK/facebook-cf-sdk#19]
Steps taken:
1. created a "facebook" subdir in examples/website to accommodate the "import facebook.sdk.FacebookApp;" in index.cfm of the website example;
2. copied "sdk" subdir to /examples/website/facebook
3. set the facebook API key and secret
4. loaded the /examples/website/inex.cfm

Result:

Invalid CFML construct found on line 497 at column 78.
ColdFusion was looking at the following text:
{
The CFML compiler was processing:
    A script statement beginning with private on line 497, column 9.
The error occurred in C:\inetpub\wwwroot\fbsdk\examples\website\facebook\sdk\FacebookApp.cfc: line 497
495 :   }
496 :  
497 :   private String function getUrl(String path = "", Struct parameters = {}) {
498 :       var key = "";
499 :       var resultUrl = "https://www.facebook.com/" & arguments.path;

**Comment by benorama** [comment]
Are you sure you are running ColdFusion 9.0.1 (and not 9.0.0) ?
If not, you must apply the 9.0.1 update to the Facebook SDK:
http://www.adobe.com/support/coldfusion/downloads_updates.html
(recommanded update)

**Comment by dejannenov** [comment]
FYI - the issue was that Application variables were disabled on the server.
