### ISSUE TITLE
Little bug breaks example

### ISSUE THREAD

**Issue by iotashan** [TheRealAgentK/facebook-cf-sdk#2]
Related to my other issue.

FacebookApp.cfc:428 needs a "var" in it, otherwise throws an error

for (var keyValue in keyValues) {

**Comment by benorama** [comment]
There is already a var declaration for keyValue at L:425.
I don't put it inside the for loop because it breaks syntax coloring on ColdFusion Builder... ;)

On which version of ColdFusion does it throw an error ?
Have you downloaded the latest version of the SDK (beta3) ?
