### ISSUE TITLE
getPageAccessToken

### ISSUE THREAD

**Issue by jfrux** [TheRealAgentK/facebook-cf-sdk#20]
What's the best way to handle this?
Am I missing it?
BTW, love the work you've done here - this is fantastic and very clean.

**Comment by jfrux** [comment]
I went ahead and forked a getPageAccessToken() function in FacebookApp.
However, I'm thinking it might make more sense that during the authorization process, if "manage_pages" was authorized then it would "store" or persist the "/me/accounts" data which contains all the API's into a struct referenced by the page id if possible.  I haven't familiarized myself with this SDK code enough to make a decision as to where to place this logic.

**Comment by benorama** [comment]
Hi JoshuaIRL,

Thanks you for the suggestion: I have added the getPageAccessToken to FacebookGraphAPI.
To use it, you just need to create a FacebookGraphAPI instance with the user access token.

I've just pushed the v3.1.1-beta4 which include those changes.

Thanks!

**Comment by jfrux** [comment]
benorama,

Sorry to bring this up again... but just upgraded to beta4, doesn't getPageAccessToken() belong in FacebookApp.cfc with the rest of the access token functions? or am I not understanding this correctly?
Is it because it requires FacebookApp user access token before we can get a page access token?

**Comment by benorama** [comment]
You can find the getPageAccessToken() method in FacebookGraphAPI.cfc.
It requires a user access token.

I've tried to keep all the graph API related methods in the FacebookGraphAPI.cfc.
