### ISSUE TITLE
getLoginUrl parameters formatting

### ISSUE THREAD

**Issue by nickmcgee** [TheRealAgentK/facebook-cf-sdk#22]
Seems to be isolated to getLoginUrl. The example code doesn't work:

``` coldfusion
parameters  = {scope = SCOPE, parameter = VALUE};
loginUrl    = facebookApp.getLoginUrl(parameters);
```

It only works when the parameter is quoted:

``` coldfusion
parameters  = {'scope' = SCOPE, 'parameter' = VALUE};
loginUrl    = facebookApp.getLoginUrl(parameters);
```

**Comment by okjim3GH** [comment]
Are you running cf9 or cf9.01? That looks like a cf9 issue. This SDK requires 9.01.

**Comment by nickmcgee** [comment]
No we're running 9,0,1,274733.

**Comment by benorama** [comment]
Indeed, this should work on 9.0.1. 
What error message do you get?

**Comment by nickmcgee** [comment]
No error message, the parameters are just ignored.

**Comment by benorama** [comment]
I think I found the reason for that.
When using {scope = SCOPE, parameter = VALUE}, ColdFusion convert it to a struct with uppercase keys.
When using {'scope' = SCOPE, 'parameter' = VALUE}, ColdFusion convert it to a struct and keep the case.

In the current SDK and the example, the scope parameter becomes uppercased in the generated login url and Facebook probably want lowercase keys in the query string.
I'm going to lower case keys in the serializeQueryString method in the FacebookBase.cfc, it should solve this issue.

It will be in the next release of the SDK. 
Thanks !
