### ISSUE TITLE
import statement not working in CF 8

### ISSUE THREAD

**Issue by kjuliff** [TheRealAgentK/facebook-cf-sdk#23]
I read elsewhere where someone had a similar problem. I am getting the following on website/index.cfm

However I do not have access to CF 9 for this project. Is there a workaround?

Invalid CFML construct found on line 20 at column 8. ColdFusion was looking at the following text:

facebook.sdk.FacebookApp

The CFML compiler was processing:

```
* A script statement beginning with import on line 20, column 1.
* A cfscript tag beginning on line 19, column 2.
```

**Comment by benorama** [comment]
Sorry, CF9.0.1 is required to run this SDK. 
It is 100% implemented in cfscript.
