### ISSUE TITLE
this is related to issues/18 - OAuthException - Code was invalid or expired

### ISSUE THREAD

**Issue by pbedi** [TheRealAgentK/facebook-cf-sdk#25]
you suggested to ignore it, i tried to ignore it and let it go to next step but it is not returning user access token from the call 
facebookApp.getUserAccessToken()

what should we do? I am using the latest code beta 4, and getting this error, what should I do?

**Comment by benorama** [comment]
Could you give us more detail with some example code to reproduce this bug?
Thanks.

**Comment by pbedi** [comment]
Hi Ben,
I got it sorted by log out from Facebook, clearing my browser's cache, and closing the browser and starting it again, but the problem I was getting was after following code:

import facebook.sdk.FacebookApp;
            import facebook.sdk.FacebookGraphAPI;

```
        // Replace this with your appId and secret
        local.APP_ID = application.facebook.APP_ID;
        local.SECRET_KEY = application.facebook.SECRET_KEY;
        local.SCOPE = application.facebook.SCOPE;

        // Create facebookApp instance
        local.facebookApp = new FacebookApp(appId=local.APP_ID, secretKey=local.SECRET_KEY);

        // See if there is a user from a cookie or session
        local.userId = local.facebookApp.getUserId();
        if (local.userId) {
            try
            {
                local.userAccessToken = local.facebookApp.getUserAccessToken();
            }
            catch (Any e)
            {
                rc.message = ['Session Expired, try again!'];
                variables.fw.redirect('login.handleFaceAuth','message') ;
            }
```

Thanks, 

other thing I use logout url in cfhttp call but it doesn't log me out, do I need to do it in normal browser's address bar?

**Comment by benorama** [comment]
The logout Url cannot be used "server-side", it must be called from the user browser (with all the cookie/session from Facebook.com).

If you want to logout the user from your app AND from Facebook.com, you must use the JS SDK FB.logout() method or the logout Url on the client-side.

If you want to logout the user only from your app, you can use CF Facebook Graph API invalidateUser() method (it will clear the session and the cookie for you). But if it will not logout the user from Facebook.com.

**Comment by Moozly** [comment]
Hi,

Where is the invalidateUser() method? I couldn't find it in Facebook documentation...
Thanks

**Comment by benorama** [comment]
It is available FacebookApp.cfc (the function is located in FacebookBase.cfc that extends all SDK CFCs).

**Comment by Moozly** [comment]
How can it be reached? it wasn't recognized...

**Comment by benorama** [comment]
What happens when you call facebookApp.invalidateUser()
