### ISSUE TITLE
Facebook all.js error in Firefox8/Firebug ... Proxy.InstallTrigger

### ISSUE THREAD

**Issue by scottmberry** [TheRealAgentK/facebook-cf-sdk#27]
Fresh FF8.0 install, fresh Firebug 1.8.4. No other browsers error and FF built in web console has no error. Can't reproduce it with other developers but still can't figure out what is causing it. Any insight? Nothing seems to be broken, all functions work. 

uncaught exception: Error: Permission denied for http://static.ak.facebook.com to get property Proxy.InstallTrigger
http://connect.facebook.net/en_US/all.js
Line 9

**Comment by VosAndHowden** [comment]
I notice the same issue on my install and can't figure out the cause for it either.

**Comment by benorama** [comment]
This something linked to the Facebook JS SDK... So I've no idea.
Probably a Facebook bug. Wait to see if it is resolve in next weekly release.
Have you checked OAuth migration in your app settings?

**Comment by scottmberry** [comment]
I was sure it was something from the FB side, just haven't seen any conversations about it and it is not consistent. It's been going on for a while, somewhat timed with the launch of FF8 but again it's hard to confirm since it only shows in Firebug. 

Can you explain the OAuth migration question? In my settings I have 

oauth     : true

That's all I know!

**Comment by benorama** [comment]
Indeed, that's strange.
If you manage to reproduce the problem, please describe exactly what you did step by step.

For OAuth, if you have selected the OAuth 2.0 migration settings, it's fine.

Thanks.

**Comment by scottmberry** [comment]
There really is nothing to do to reproduce it. I have completely wiped FF and all data, reinstalled 8.0 from a fresh download and I get that specific issue for each API call on a page from FB. So it does not appear at all to be related to your library, I guess I was hoping you or someone here might have the same issue. For example using your API implementation: 

uncaught exception: Error: Permission denied for https://s-static.ak.facebook.com to get property Proxy.InstallTrigger
FB.provide('JSON',{stringify:function(...]=FB.JSON.stringify(d);}return a;}}); 

Or just using straight FB javascript for a different projec (completely different site, codebase, two like buttons on a page): 
uncaught exception: Error: Permission denied for https://www.facebook.com to get property Proxy.InstallTrigger
FB.provide('JSON',{stringify:function(...]=FB.JSON.stringify(d);}return a;}});
all.js (line 9)
uncaught exception: Error: Permission denied for https://www.facebook.com to get property Proxy.InstallTrigger
FB.provide('JSON',{stringify:function(...]=FB.JSON.stringify(d);}return a;}}); 

Same issue either way, so not specific to you. But odd that it exists (only in Firebug) and that I can't find anyone else reporting it.

**Comment by ptasker** [comment]
I'm also having the same issue. Just cropped up today:

uncaught exception: Error: Permission denied for https://s-static.ak.facebook.com to get property Proxy.InstallTrigger

**Comment by scottmberry** [comment]
Phew, someone else! Glad it isn't just me. Peter, is this FF8 with Firebug? I don't see the regular console on FF showing any errors nor any other browser. It doesn't seem to affect any functionality either.

**Comment by ptasker** [comment]
Ya it's FF 8 with Firebug for me too. I have no idea where it's coming from.

But it seems to be in:

FB.api('/me?access_token=' + accesstoken, function (response) {
    facebookID = response.id;

```
})
```

If I remove this, my app breaks, but no more errors.

**Comment by benorama** [comment]
This looks like a Facebook JS SDK bug.
Have try to ask your question on the official support forums?
http://facebook.stackoverflow.com/

Here is a similar question :
http://facebook.stackoverflow.com/questions/8135999/facebook-connect-error-in-firefox-8-0

**Comment by andycole** [comment]
Worth noting this is only happening for me since FF8 upgrade. It's been working for months using the same set-up (FF 8, latest firebug, latest FB code etc.)

**Comment by localpcguy** [comment]
Just noticed this (or a very similar error) in line 9 of all.js from the Facebook SDK.  I can only see it if I use Chrome and have pause on all exceptions turned on.  Otherwise it doesn't seem to show up and doesn't seem to actually break any functionality, either mine or Facebook's.

**Comment by ejvalmores** [comment]
hi, 

anyone got this error lately?   I have an app using facebook js sdk and it was working a week ago.  Now I cant even do a simple FB.getLoginStatus.  getting this error on page load:

Timestamp: 3/19/12 3:08:34 PM
Error: uncaught exception: Error: Permission denied for https://www.facebook.com to get property Proxy.InstallTrigger

Could really use the help or any insights.  Thanks!! :)
