### ISSUE TITLE
index page

### ISSUE THREAD

**Issue by aviva** [TheRealAgentK/facebook-cf-sdk#3]
first of all, thanks so much for the sdk!!!
I uploaded the pages in 'example', set up my app just like you said, and
i get this error:

The error occurred in .....\sdk\FacebookApp.cfc: line 361
Called from .....\friend\sdk\FacebookApp.cfc: line 340
Called from .....\friend\sdk\FacebookApp.cfc: line 246
Called from .....\friend\index.cfm: line 40

You have attempted to dereference a scalar variable of type class coldfusion.runtime.Array as a structure with members. 

(my test page is at: http://apps.facebook.com/friendweek/)

when this is run:
    private String function generateParametersSignature(required Struct parameters, required String secretKey) {
        var buffer = createObject("java","java.lang.StringBuffer").init("");
        var key = "";
        var sortedKeys = listToArray(listSort(structKeyList(arguments.parameters),"textnocase", "Asc", ","));
        for (key in sortedKeys) {
            buffer.append(key & "=" & arguments.parameters[key]);
        }
        buffer.append(arguments.secretKey);
        return LCase(hash(buffer.toString()));
    }

i looked at your test app on facebook and it works. Not sure what i'm doing wrong.

**Comment by benorama** [comment]
Have you enabled  all migration settings (session and OAuth 2.0) in "Advanced parameters" of your app?
It might solve your issue.

**Comment by brihol44** [comment]
Hello, I'm getting a similar error but on the next function. I'm not sure what you meant by "enabling all the migration settings (session and OAuth 2.0) in "Advanced parameters" of your app?"

Error of...

You have attempted to dereference a scalar variable of type class coldfusion.runtime.Array as a structure with members. 

425 :       var keyValues = listToArray(replace(arguments.queryString,'"', '', 'ALL'), "&");
426 :       var parameters = structNew();
427 :       for (keyValue in keyValues) {
428 :           if (listLen(keyValue, "=") == 2) {
429 :               parameters[listFirst(keyValue,"=")] = listLast(keyValue,"=");

private Struct function parseQueryStringParameters(required String queryString) {
        var keyValue = "";
        var keyValues = listToArray(replace(arguments.queryString,'"', '', 'ALL'), "&");
        var parameters = structNew();
        for (keyValue in keyValues) {
            if (listLen(keyValue, "=") == 2) {
                parameters[listFirst(keyValue,"=")] = listLast(keyValue,"=");
            }
        }
        return parameters;
    }

**Comment by aviva** [comment]
the issue was my hosting company did not have the 9.0.1 patch. Once i notified them and they installed it, the cfc worked just fine. thanks.

**Comment by benorama** [comment]
To aviva: cool.

To brihol44: the advanced parameters are available in your Facebook App administration page, where you can configure your app.
You can access your Facebook Apps here :
http://www.facebook.com/developers/apps.php
