### ISSUE TITLE
Offline Access Deprecation Updates?

### ISSUE THREAD

**Issue by jfrux** [TheRealAgentK/facebook-cf-sdk#33]
This is separate issue from my other issue... but...
As per this: https://developers.facebook.com/docs/offline-access-deprecation/
Does this CF sdk support this change yet?
Or have any idea what needs done to fix this?

**Comment by benorama** [comment]
You should be able to request for a token valid during 2 months now.
It is up to you to store the expiration time and to ask for a new token before it expires.

To exchange your token, I committed today an update to FacebookGraphAPI : the getOAuthAccessToken can take now an "exchangeToken" argument.
Ex. : facebookGraph.getOAuthAccessToken(clientId=CLIENT_ID, clientSecret=CLIENT_SECRET, exchangeToken=VALID_TOKEN)
