### ISSUE TITLE
missing semicolon

### ISSUE THREAD

**Issue by okjim3GH** [TheRealAgentK/facebook-cf-sdk#36]
FacebookGraphAPI.cfc  line342 missing semicolon  (inside getOAuthAccessToken method )

httpService.addParam(type="url", name="grant_type", value="fb_exchange_token")

**Comment by benorama** [comment]
Indeed, this is corrected on our dev branch.
We should push a new release by the end of the week with new methods for timeline pages (page app image update, page info update...).
