### ISSUE TITLE
OAuthException on connect disconnect

### ISSUE THREAD

**Issue by wobstyr** [TheRealAgentK/facebook-cf-sdk#38]
I am trying to get this to work, however works fine until you try connect or disconnect (signin / signout)

this is with a basic standard cut and past of code. 

OAuthException - Code was invalid or expired. This may be because the user logged out or may be due to a system error. [code=100] The error occurred on line 75.

**Comment by Spiderwoman** [comment]
Solution for this was posted in the solved issues

https://github.com/affinitiz/facebook-cf-sdk/issues/31
