### ISSUE TITLE
dereference a scalar variable error

### ISSUE THREAD

**Issue by foureyesweb** [TheRealAgentK/facebook-cf-sdk#4]
Using the webiste method when I login I get the following error and I am not sure why this would be.  I am using the latest version.

You have attempted to dereference a scalar variable of type class coldfusion.runtime.Array as a structure with members.

The error occurred in C:\WebDev2\farcry-6\projects\bergen\www_dev\affinitiz_facebook\src\facebook\sdk\FacebookApp.cfc: line 427
Called from C:\WebDev2\farcry-6\projects\bergen\www_dev\affinitiz_facebook\src\facebook\sdk\FacebookApp.cfc: line 261
Called from C:\WebDev2\farcry-6\projects\bergen\www_dev\affinitiz_facebook\examples\website\index.cfm: line 39

425 :       var keyValues = listToArray(replace(arguments.queryString,'"', '', 'ALL'), "&");
426 :       var parameters = structNew();
427 :       for (keyValue in keyValues) {
428 :           if (listLen(keyValue, "=") == 2) {
429 :               parameters[listFirst(keyValue,"=")] = listLast(keyValue,"=");

Any assistance is greatly appreciated.

**Comment by foureyesweb** [comment]
Hmmm, I think I need to install the 9.01 patch!

**Comment by mygithub747** [comment]
Hello, I have tried updating to latest CF 9 update, but looks like this error won't go away, I wonder which version author is running this SDK?
