### ISSUE TITLE
Error in FacebookBase.cfc on returned status code

### ISSUE THREAD

**Issue by seanford** [TheRealAgentK/facebook-cf-sdk#40]
Started receiving an error on successful logins on line 80.  Since all that is is a throw with the Status code, and it was outputting a "200" (no ok), I gathered that Facebook is returning a status code of 200 without the OK.

Changed line 77 to read:

```
    } else if (isSimpleValue(response.fileContent) && ( response.statusCode == "200 OK" || response.statusCode == "200" ) ) {
```

That will accept both a status code of 200 OK or 200 as a valid response.

**Comment by benorama** [comment]
Good catch!
I'll push the fix very soon.
