### ISSUE TITLE
External Site Integration is broken

### ISSUE THREAD

**Issue by CFPro** [TheRealAgentK/facebook-cf-sdk#41]
My site stopped working with FB connect, I went to try to use your external site integration example at

http://affinitiz.com/facebook-cf-sdk/examples/website

It states:

Sorry, an error occurred.
It has been automatically recorded for further correction.

Please look into this problem asap, my users cannot login

Thank you

**Comment by CFPro** [comment]
The example seems to be working again, what changed?

**Comment by CFPro** [comment]
My site is also working again, what 3rd party was down? FB? FB showed 100% health during the downtime.

**Comment by benorama** [comment]
It was probably a Facebook bug because we did not change anything on our side... ;)
Even if FB platform uptime is 100%, it does not mean that they don't have bugs.

Here is the list of current bugs :
https://developers.facebook.com/bugs/

**Comment by CFPro** [comment]
I agree with you, I am glad the problem went away.
