### ISSUE TITLE
CF10 Compatibility

### ISSUE THREAD

**Issue by seanford** [TheRealAgentK/facebook-cf-sdk#42]
Changed the following function in FacebookBase.cfc as follows:

public Boolean function isPersistentDataEnabled() {
        if (ListFirst(server.coldfusion.productversion,",") GTE 10) {
            return getApplicationMetaData().sessionManagement;     // CF10 compatible
        } else {
        return application.getApplicationSettings().sessionManagement;
        }
}

Otherwise you get a 500 error in CF10 as the undocumented method has been replaced by the new public method.

**Comment by benorama** [comment]
I just pushed this fix.
Thanks!

**Comment by joejoecc** [comment]
FYI ... I don't see this on the latest version.

**Comment by benorama** [comment]
Indeed, fix was not pushed to GitHub master branch.
It's done now.

Thanks.
