### ISSUE TITLE
No refresh after successful facebook login

### ISSUE THREAD

**Issue by tunameltdown** [TheRealAgentK/facebook-cf-sdk#43]
I'm running into a peculiar issue with logging in via the server side redirect. Using the example in the website directory I can log into facebook but when the index.cfm page refreshes it tells me that I'm not connected. If I keep a second browser window open to my facebook page I can see that I am connected. In fact, I can watch that browser window change status as I log in and out using the links on the example page. If I click the "login via server side redirect" button again I don't get the facebook login dialog but the page does refresh and show correctly that I am now connected. I've tried to reproduce on the affinitiz example page but that page seems to work fine. I have the absolute latest version. Any insight would be appreciated. Could the issue be with the actual app settings at facebook? Really scratching my head here.

**Comment by benorama** [comment]
I strongly recommend to login via the Facebook JS SDK.
It provides a better user experience.

**Comment by tunameltdown** [comment]
Thanks, Benoit. I'll give it a try. Thanks again for your excellent work on porting this in the first place.

Geoff

---

Geoffrey Fudge
www.genuinepixels.com
128 Peckham Avenue
Middletown, RI 02842

ph: 401.225.0771
