### ISSUE TITLE
OAuthException

### ISSUE THREAD

**Issue by jricheyicnd** [TheRealAgentK/facebook-cf-sdk#44]
It seems the auth token keeps expiring after a couple days:

"OAuthException - Error validating access token: Session has expired at unix time 1337900400. The current unix time is 1339436022."

How can I force the component to grab a new access token when the old one expires?

**Comment by benorama** [comment]
You might want to use FacebookApp exchangeAccessToken(currentValidToken) method. It will return a new token valid during 2 months (by default token are only valid during 2 hours).
