### ISSUE TITLE
Refresh loop

### ISSUE THREAD

**Issue by joejoecc** [TheRealAgentK/facebook-cf-sdk#47]
I implemented your Facebook Javascript SDK into my site.  Occasionally, a user will experience the page going into a "page refresh loop" after authenticating.  I've only been able to replicate it once, but I was unable to troubleshoot it since it didn't happen again.  Any tips would be great.  I didn't alter the page much, but since I did alter it the error may be on my end.  Thanks.

**Comment by joejoecc** [comment]
@jeaguilar have you encountered this issue?

**Comment by jeaguilar** [comment]
Sorry, joejoecc. I'm afraid not. If you want to post any code I'd be happy to throw a pair of fresh eyes on it.

**Comment by wiktorazas** [comment]
i have similar issue, but i'm using no JavaScript. Keeps me in the loop to, and to reproduce this I delete all cash, cookies and so on, then it keeps user in the loop returning userid 0. 
for more details: I just published this issue: https://github.com/affinitiz/facebook-cf-sdk/issues/51
