### ISSUE TITLE
"You have attempted to dereference a scalar variable" error...

### ISSUE THREAD

**Issue by rnehring** [TheRealAgentK/facebook-cf-sdk#5]
Hey man, great work on this project, and it works just fine for me as a user connecting to the app you host on examples, but I am unable to get it working on my server.  I got it installed just fine and everything seems to be working initially when you load the test-url.  The page loads itself ok and your public data at the bottom loads fine, but when you try to actually Login/Connect with Facebook you get the error. (http://www.controltower.me/facebook-cf-sdk/examples/website/ <---my test install online here if you'd like to see the error live). 

Oops:  Just saw that it technically requires CF9.0.1... I'm on Newtek/Crystaltech hosting and they haven't fully upgraded yet... does this really require 9.0.1 or is there some sort of workaround ? I'd love to be able to play with this some more, but they're seriously draggin on the 9.0.1 install so if its some sort of integral CF9.0.1 only array I'm unaware of, then I'll end up having to wait .. either way nice work! 

thanks!
Ryan

The web site you are accessing has experienced an unexpected error.
Please contact the website administrator.

The following information is meant for the website developer for debugging purposes.
Error Occurred While Processing Request
You have attempted to dereference a scalar variable of type class coldfusion.runtime.Array as a structure with members.

The error occurred in D:\Inetpub\DomainID205884\facebook-cf-sdk\examples\website\facebook\sdk\FacebookApp.cfc: line 361
Called from D:\Inetpub\DomainID205884\facebook-cf-sdk\examples\website\facebook\sdk\FacebookApp.cfc: line 457
Called from D:\Inetpub\DomainID205884\facebook-cf-sdk\examples\website\facebook\sdk\FacebookApp.cfc: line 256
Called from D:\Inetpub\DomainID205884\facebook-cf-sdk\examples\website\index.cfm: line 37

359 :       var key = "";
360 :       var sortedKeys = listToArray(listSort(structKeyList(arguments.parameters),"textnocase", "Asc", ","));
361 :       for (key in sortedKeys) {
362 :           buffer.append(key & "=" & arguments.parameters[key]);
363 :       }

**Comment by rnehring** [comment]
I'm an idiot... just saw the other posts & it looks like it is 9.0.1 only... you can delete this lol

**Comment by mygithub747** [comment]
Hello, I am running 9,0,1,274733 CF Enterprise and this problem just won't go away, anything special you did on the server configuration to make this work? Please help.

Thanks

**Comment by benorama** [comment]
We just released a new version of the SDK with plenty of new stuff. Can you try to download it to see if it solves your issue?

**Comment by mygithub747** [comment]
I downloaded and installed the new version of the SDK and everything seems to be working ;-)

**Comment by rnehring** [comment]
I was actually lucky enough to talk my host into upgrading so the problem went away for me when I did that, but I'm excited to hear theres a new version up and I'm gonna DL it now!
