### ISSUE TITLE
IE 9 issue

### ISSUE THREAD

**Issue by jsttriit** [TheRealAgentK/facebook-cf-sdk#50]
We are having an issue with IE9.  

Facebook login works fine when it is on our site but the exact same code keeps sending people back to the login button when they try to login to the app within Facebook as an iFrame.

Any thoughts?

Works here:
http://www.energeeinc.com/facebook/

Not here:
https://apps.facebook.com/energeeinc/

Rob

**Comment by TheRealAgentK** [comment]
Closed because can't get to links to replicate.
