### ISSUE TITLE
SSL cfhttp problem

### ISSUE THREAD

**Issue by tacshooter** [TheRealAgentK/facebook-cf-sdk#52]
I tried importing the cert, but I guess that wasn't it, as I still  can't even run the examples. I get the old: "Connection Failure. Status code unavailable." error. Does anyone have any ideas for getting around this? Like I said, I exported the cert from visiting the url in the browser and imported it into the keystore, but it doesn't seem to have helped... If I go into getObject() in FacebookGraphAPI.cfc and change the url to http, then everything works fine, but most requests have to be https...

Thanks,
Ferg

**Comment by TheRealAgentK** [comment]
Ferg, do you still have this issue? I can't reproduce an SSL issue with my setup, so you'd need to specifiy quite explicitly and clearly the steps to reproduce your setup.

**Comment by tacshooter** [comment]
This was about a year and a half ago. I don't even remember what project I was using this for or what I did to get around it in the end. I'm guessing that I got it figured out or went a different way. Thanks anyway though.

**Comment by TheRealAgentK** [comment]
Ok, no prob, thx for the feedback.
