### ISSUE TITLE
GetPage() return empty struct after the acceptance of terms applications or after a simple link

### ISSUE THREAD

**Issue by sined79** [TheRealAgentK/facebook-cf-sdk#53]
Hi,

I have a problem with my application.
I started my dev from this example: (examples/app/index.cfm) 
Firstable, I use isPageLiked. If the page is liked, the user can access to the application, he must accept facebook terms and scope before (login facebook). 
When he accept that, reload of the page but the function getPage return an empty struct, thus the screen to like the page come-back. 
With a "F5", the application begin.
I have the same behavior when I click on a simple link in my application

Can you help me ? 

Thank you :-)

Best regards
Denis

**Comment by TheRealAgentK** [comment]
Denis, can you please provide a reproducible test case for this. Happy to look at it then.

**Comment by TheRealAgentK** [comment]
Haven't heard back from the reporter, closed.
