### ISSUE TITLE
Download page no longer exists.

### ISSUE THREAD

**Issue by boughtonp** [TheRealAgentK/facebook-cf-sdk#54]
Both RIAForge and http://affinitiz.com/facebook-cf-sdk/ point to https://github.com/affinitiz/facebook-cf-sdk/downloads

However that page states "There aren’t any uploads for this repository" since GitHub discontinued that functionality - see https://github.com/blog/1302-goodbye-uploads

Might want to update the download links to https://github.com/affinitiz/facebook-cf-sdk/tags or something else?

**Comment by TheRealAgentK** [comment]
Fixed in https://github.com/TheRealAgentK/facebook-cf-sdk/commit/1f7235ae0f15dd5c61e26193c8357890c987963f (as much as it is in my power at this stage).
