### ISSUE TITLE
Keeps looping after login

### ISSUE THREAD

**Issue by mygithub747** [TheRealAgentK/facebook-cf-sdk#6]
I have installed CF trial 9, did the latest update, followed SDK installaton procedure, website shows up fine using http://localhost/facebook-cf-sdk/examples/website/.  Updated FB settings to point to this URL etc.. I click login button, logins in fine, but then it goes into infinite loop.

Any idea how to resolve this problem.

Please help.

Thanks
Rusty

**Comment by benorama** [comment]
We just released a new version of the SDK with plenty of new stuff. Can you try to download it to see if it solves your issue?
One important point, to develop connect with Facebook : your site must run on a server accessible by Facebook. It cannot be localhost... ;)

**Comment by mygithub747** [comment]
I downloaded the new SDK and looks like everything is working as supposed to :-).

Thanks Benorama.
