### ISSUE TITLE
fbs_ cookie verification

### ISSUE THREAD

**Issue by ojhilt** [TheRealAgentK/facebook-cf-sdk#9]
Hey good library, given the god aweful piece of _ahem_ that is the facebook documentation this is a big help to the CF community.  Only one problem I've seen so far and as I've just spent an afternoon fixing it for myself I thought I may as well share, save others the pain.

You have a method to parse the contents of the (very useful) fbs_[appid] cookie, the only problem is you don't verify its authenticity, I don't blame you its a total arse but its worth it when security matters.  Below is a function I've written to do just that, hope you don't mind I left the integration to the experts :)

<cffunction name="checkFbsCookie" access="private" returntype="numeric" output="false" hint="Verify the fbs_ cookie is real and valid, return the facebook id if it is">
        <cfargument name="cookieVal" type="string" required="true" hint="the exact value extracted from the fbs_ cookie">

```
    <cfscript>
        // New struct for the values and remove those pesky quotes from the cookie string
        var strCookie = structnew();
        var trimmed = mid(cookieVal,2,len(cookieVal)-2);
        var valid = 0;

        // Just create a simple struct with all the values in
        for(i=1; i LTE listLen(trimmed,'&');i=i+1) 
        {
            key = listgetat(listGetAt(trimmed,i,'&'),1,'=');
            value = listgetat(listGetAt(trimmed,i,'&'),2,'=');
            structInsert(strCookie, key, value);
        }

        // Do what we need to do to the cookie value to verify it
        var payload = replacenocase(trimmed,'sig=#strCookie.sig#','');
        var payload = replacenocase(payload,'&','','all');

        // The important part, if they dont match the cookie is bogus!
        // Substitute your app secret code!
        if(hash(payload & _appSecret) eq ucase(strCookie.sig))
            valid = 1;

    </cfscript>

    <!--- This part is work in progress, you may want to return the whole sturct, I did not --->
    <cfif valid>
        <cfreturn strCookie.uid>
    <cfelse>
        <cfreturn 0>
    </cfif>
</cffunction>
```

**Comment by benorama** [comment]
We do validate the user session signature with the validateUserSession method, isn't it?
